# Generated by Django 4.2.4 on 2023-08-06 23:31

from django.db import migrations

def add_channel_partner(apps, schema_editor):
    ChannelPartner = apps.get_model('arva_field_management_app', 'ChannelPartner')

    channel_partner_data = [
        {
            'name': 'Tut Avondale',
            'address': '123 Main St',
            'phone_number': '409-555-7890',
            'email': 'part1@arva.com'
        },
        {
            'name': 'Cos Riverside',
            'address': '123 Main St',
            'phone_number': '305-456-1212',
            'email': 'part2@arva.com'
        }
    ]
    
    for channel_partner in channel_partner_data:
        ChannelPartner.objects.create(**channel_partner)

def add_client(apps, schema_editor):
    Client = apps.get_model('arva_field_management_app', 'Client')
    ChannelPartner = apps.get_model('arva_field_management_app', 'ChannelPartner')

    client_data = [
        {
            'channel_partner': ChannelPartner.objects.get(name='Tut Avondale'),
            'name': 'Miguel',
            'address': '14 Flow Cove',
            'phone_number': '331-982-8730',
            'email': 'miguel@gaea.com'
        },
        {
            'channel_partner': ChannelPartner.objects.get(name='Cos Riverside'),
            'name': 'Samantha',
            'address': '898 Rest Easy St',
            'phone_number': '539-241-4962',
            'email': 'sam@terra.net'
        },
        {
            'channel_partner': ChannelPartner.objects.get(name='Tut Avondale'),
            'name': 'John',
            'address': '40385 N. Houston Rosslyn Rd',
            'phone_number': '409-455-4207',
            'email': 'john@pachamama.org'
        }
    ]

    for client in client_data:
        Client.objects.create(**client)



class Migration(migrations.Migration):

    dependencies = [
        ('arva_field_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_channel_partner),
        migrations.RunPython(add_client)
    ]
